### ISSUE TITLE
query builder issue 

### ISSUE THREAD

**Issue by Musawarkhn** [Analog-Labs/testnet_issue_tracker#3]
**Description**

cant click on next button when the testrun was successful, i deploy my view and then next button came when i click on it so a cross sign was showing on my mouse arrow

**Expected vs. Actual Behavior**
previsouly it was working fine when clicked on next so we got successful deploymnet

 
![WhatsApp Image 2024-04-18 at 18 17 16](https://github.com/Analog-Labs/testnet_issue_tracker/assets/167439220/76cf97ed-1143-458f-890e-9e6f6bf21684)

**Comment by harshil8819** [comment]
@Musawarkhn You've to add one Tag and Description as well. You can check on (i) message.

cc: @Musawarkhn

**Comment by Musawarkhn** [comment]
Ok ok, I know i know but previously it was working without description. But
it resolved when i restarted my Pc
Thank You
